### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by gufoe** [zackify/slackify#1]
Hi, I get the following error on Debian sid, nodejs v4.2.2.

```
~$ memeify

server/app.js:16
slack.on('open', () => {
                  ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

I solved this changing line 16 to:

```
slack.on('open', function() {
```

**Comment by zackify** [comment]
You don't seem to be on node 4.2.2. Are you sure? Because that syntax is supported.

**Comment by zackify** [comment]
Can you run 'node -v' for me?

**Comment by gufoe** [comment]
My fault, I had node legacy installed, so `nodejs` is actually at 4.2.2 but `node` at 0.10.40.

**Comment by zackify** [comment]
Cool! Glad you figured it out. I'm just happy someone else is using this!

**Comment by gufoe** [comment]
Actually I'm writing something similar for Telegram and I thought it might be useful to check how you did this! :)
